version: '3'

services:

  #  Controle de Series
  app:
    container_name: controle-series
    build:
      context: ./
      dockerfile: docker/api.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # The Web Server
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 8990:80

  
  # The Database
  database:
    container_name: mysql_database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=testes"
      # - "MYSQL_ROOT_PASSWORD="
    ports:
      - 8991:3306

volumes:
  dbdata: